language: csharp
sudo: false
mono: none
dotnet: 2.0.0
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

os:
  - linux

script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore -r $runtime; fi
  - dotnet build -c Release
  - cd $TEST_PATH
  - dotnet add ./$TEST_PROJECT package xunit.runner.console --version $XUNIT_RUNNER_VERSION
  - dotnet restore ./$TEST_PROJECT -r $runtime -f $TEST_FRAMEWORK
  - dotnet build ./$TEST_PROJECT -c Release -f $TEST_FRAMEWORK
  - dotnet test ./$TEST_PROJECT